name: Publish Site
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('./yarn.lock') }}

      - name: Install Node Modules
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn

      - name: Build Static Files
        run: ls -al src/templates && yarn clean && yarn build

      - name: Push to ardelio.github.io
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'public'
          destination-github-username: 'ardelio'
          destination-repository-name: 'ardelio.github.io'
          user-email: asceresini@gmail.com
          target-branch: main
