name: Publish Site
on: push
jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules

      - name: Install Node Modules
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn

      - name: Build Static Files
        run: yarn build

      - name: Add CNAME to Build
        run: cp CNAME public/.

      - name: Prepare Commit
        run: |
          cd public
          git init .
          git add --all
          git -c user.email=asceresini@gmail.com user.name='GitHub Actions' commit -m "Site update at ${DATE}"

      - name: Force Push
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd public
          git push --force --quiet "https://${API_TOKEN_GITHUB}@github.com/ardelio/ardelio.github.io.git" master:master 2>%1 > /dev/null
